ORIGINAL_LINK_MAX_LENGTH = 256
SHORT_ID_MAX_LENGTH = 16
SHORT_ID_LENGTH = 6
MAX_ATTEMPTS = 10
ALLOWED_CHARS = (
    'abcdefghijklmnopqrstuvwxyz'
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    '0123456789'
)
SHORT_ID_PATTERN = r'^[a-zA-Z0-9]+$'
FORBIDDEN_SHORT_IDS = ['files']
